---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/.devcontainer/"
    schedule:
      interval: "daily"
    target-branch: "develop"
