---
name: Build and Scan Docker Image with SBOM

run-name: Build and Scan Docker Image with SBOM on ${{ github.ref_name }}

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - develop
    paths:
      - ".devcontainer/Dockerfile"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-and-scan:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        # v5.0.0
        with:
          persist-credentials: "false"

      - name: Set up Docker Buildx
        # yamllint disable-line rule:line-length
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435  # v3.11.1

      - name: Build Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        # v6.18.0
        with:
          context: .
          file: .devcontainer/Dockerfile
          tags: dev-container:test
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Testinfra
        run: |
          cd /opt
          python3 -m venv testinfra
          source testinfra/bin/activate
          python3 -m pip install pytest-testinfra==10.2.2

      - name: Run Testinfra tests
        run: |
          source /opt/testinfra/bin/activate
          py.test -v tests/docker_image_test.py
          deactivate

      - name: Install Syft (SBOM generator)
        run: |
          curl -sSfL \
            https://raw.githubusercontent.com/anchore/syft/v1.29.0/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (CycloneDX format)
        run: |
          syft dev-container:test -o cyclonedx-json --scope squashed \
            > sbom.json

      - name: Install Grype (Vulnerability scanner)
        run: |
          curl -sSfL \
            https://raw.githubusercontent.com/anchore/grype/v0.96.1/install.sh \
            | sh -s -- -b /usr/local/bin

      - name: Scan SBOM with Grype
        run: |
          grype --only-fixed sbom:sbom.json -o sarif=grype.sarif

      - name: Upload Grype report
        if: always() && (hashFiles('grype.sarif') != '')
        # yamllint disable-line rule:line-length
        uses: github/codeql-action/upload-sarif@f1f6e5f6af878fb37288ce1c627459e94dbf7d01  # v3.30.1
        with:
          sarif_file: grype.sarif
