---
name: Lint and Validate Shell Scripts

run-name: Linting and Validation Shell Scripts on ${{ github.ref_name }}

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - develop
    paths:
      - ".githooks/pre-commit"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Shellcheck:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: "false"

      - name: Running Shellcheck
        run: shellcheck .githooks/pre-commit
