---
name: Lint and Validate Shell Scripts

run-name: Linting and Validation Shell Scripts on ${{ github.ref_name }}

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - develop
    paths:
      - ".githooks/pre-commit"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Shellcheck:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: "false"

      - name: Running Shellcheck
        run: shellcheck .githooks/pre-commit
